apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: cloudsentro
  labels:
    app: agent-service
data:
  AZURE_TENANT_ID: PLACEHOLDER_TENANT_ID
  AZURE_CLIENT_ID: PLACEHOLDER_AGENT_SP_CLIENT_ID
  AZURE_KEYVAULT_URL: PLACEHOLDER_KEYVAULT_URI
  AZURE_AKS_RESOURCE_ID: PLACEHOLDER_AKS_RESOURCE_ID
  AZURE_SUBSCRIPTION_ID: PLACEHOLDER_SUBSCRIPTION_ID
  AZURE_RESOURCE_GROUP: rg-cloudsentro-terraform
  AZURE_STORAGE_ACCOUNT_URL: PLACEHOLDER_STORAGE_ACCOUNT_URL
  GITHUB_REPO_OWNER: PLACEHOLDER_GITHUB_OWNER
  GITHUB_REPO_NAME: infra-pulse
  GITHUB_DEFAULT_BRANCH: main
  GITHUB_APP_ID: PLACEHOLDER_GITHUB_APP_ID
  GITHUB_INSTALLATION_ID: PLACEHOLDER_GITHUB_INSTALLATION_ID
  ML_SERVICE_URL: http://ml-service:8000
