apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-service-account
  namespace: cloudsentro
  annotations:
    azure.workload.identity/client-id: PLACEHOLDER_AGENT_SP_CLIENT_ID
  labels:
    app: agent-service
    azure.workload.identity/use: "true"
