apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: cloudsentro
  labels:
    app: agent-service
spec:
  type: ClusterIP
  selector:
    app: agent-service
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
