apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-service-account
  namespace: cloudsentro
  annotations:
    azure.workload.identity/client-id: PLACEHOLDER_ML_SP_CLIENT_ID
  labels:
    app: ml-service
    azure.workload.identity/use: "true"
